apiVersion: v1
kind: ConfigMap
metadata:
  name: arrebol-config
data:
  application.properties: |
    spring.jpa.database=POSTGRESQL
    spring.datasource.driverClassName=org.postgresql.Driver
    spring.datasource.platform=postgres
    spring.datasource.url=jdbc:postgresql://localhost:5432/arrebol
    spring.datasource.username=postgres
    spring.datasource.password=admin
    spring.jpa.generate-ddl=true
    spring.jpa.hibernate.ddl-auto=update
  # The volumeName value is the name of PersistentVolumeClaim used by k8s jobs
  arrebol.json: |
    {
      "poolType":"k8s",
      "properties": [
        {
          "key":"capacity",
          "value": 20
        },
        {
          "key": "address",
          "value": "http://127.0.0.1:8001"
        },{
          "key": "namespace",
          "value": "default"
        },{
          "key": "volumeName",
          "value": "nfs"
        }
      ]
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
data:
  PGADMIN_DEFAULT_EMAIL: admin@lsd.ufcg.edu.br
  PGADMIN_DEFAULT_PASSWORD: admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: admin
  POSTGRES_DB: arrebol
---
# Run the command below to get the contents of the k8s configuration file
# kubectl config view --flatten --minify --raw
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeconfig
data:
  config: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMVENDQXBXZ0F3SUJBZ0lSQU4wTTdmNWhUbWN5eUhLeTQybGpjaDB3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa1pUWXhNakJqT0RrdE4yRmpPUzAwTUdFNUxXSXdaamN0TnpVeE56TmlaRGN3TWprdwpNQ0FYRFRJeE1EY3lNekUyTlRneE9Wb1lEekl3TlRFd056RTJNVGMxT0RFNVdqQXZNUzB3S3dZRFZRUURFeVJsCk5qRXlNR000T1MwM1lXTTVMVFF3WVRrdFlqQm1OeTAzTlRFM00ySmtOekF5T1RBd2dnR2lNQTBHQ1NxR1NJYjMKRFFFQkFRVUFBNElCandBd2dnR0tBb0lCZ1FEVldDRTBQRFpiUGJMZzVMWDZCNi9VODhLS2xwcVlIaWQvN2V4VwprcEdVVGpCUm9rZGd0NDlTdStpQU40VHgzMHFpcW1OdDYwUVEwdnlRTlRMazBYS2lIaWZqUDlwL09YRVFYdFJ2CkhSbWNONGgrazNJdVN1aGF0WlVuN3dHdStFaXV0ZExlUmJUSTdVUUROTHRpZjdOVFJ2RCtKVjFVREVOV1VqVVkKUElvTzhKQlJIam91M1Z0R3NOQ1IvOEMwN1RoaWNJYjl4bDZ2b0ZrNGFDVGNscnVscVJ4b21NSXF3OUVQbzJWSwpIWHJNTDdvQlBOam1oS2FRUmtjL1p0bkNaa2RIN0ZDTndPV011MTBOQ3NTUTc2NlF4QUZsM1psT2pXZlI2czVwCmJwR0pNU3h5UGQvVC90c0xvcDV6QjdnR0EvWENxVWVEZ0RaalVSVHcxSmZFelZoV1VXSEZ2bHhGaU51YUdORGMKZEU1c1hneGNyK0diMUJhS0gzMkl1amoyTTJSSDkxNzVMM25CWGpzOGFweUZMRHM0MTRaY01xUmpzNVBHTjIzMwoxRlhnZkxlMURXOXFoNHVjLytZMk1KL2JGUVZVeVlPMHcxNzNwQmQ2Y0xLQ29OR2J5d01kUnFKYXcrbFdEdkRoCnlWWm1YbW1TcjNOSTM0YXlQVWhibnRuTEFGTUNBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdJRU1BOEcKQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGTGh2WTFxcXZSWlFyYXp1OVZxN2lRbUR4bXlJTUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQmdRQTR6OXBIWEVjRWw2SGxEemxaT29RUHV0NmJETDZ2dXF5RXplY3VtUFp0CmxJSG5HRnJjOHA4Q3lGcHlYUFBLR3VvU2JGUEgxVldkaHVXZStQb3J4NTVBcGozZGxqVFpuMkxMYWMrZDEyL2MKeDBkNmVZZzlnQlRNSWx3UThjM3pmcUtmZ0dPdytZeGwvQ0FtQXNheUVhS1lWaWIxZkZ0eE9ERnFTYVJZUlA0bgo5eUR3dXowVW04ZzY3dFp5enNSbFdOR3gvNmxCK1U3b2szQkxGMk8rWFROSEdLRGR1ZWg1WUpWZXlrQjBjR2prCnRNMERuUHVPdVlsSTU1eS9QUXNRK3U3YnRzb1pQczI4blkzTS9QSC9md0VxVTFaR1hkVm5QbE5sUVJVcDBsUmoKZ2dNemsyWS9tb1N0V0FVY1AwU2ZJbVR0aUgrMGdGQlM4NERaTVlaY2s1Vk42cytlMDlPR0VxV3FxMUk2OG5vMwpBMWN3bkVyUXBpTlc4S0hLS3V1bmRXNmVnNmphL1Bodm11OXdZSWJ4WmJZdmZ1WmlHZWQwSEUvZnM0Z0p6cTJ5CklRNTdLVnRIdGxVK1RpQmgydll6Nzh0Z3FhUWF0M2h4eUdkU0ZVYmo1QlpVa1dtUGxYMmlJM3ZocVRQalZ4dkgKKy93MXY2RDZyckNZRnI1d25GdW5HZm89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        server: https://35.227.43.222
      name: gke_key-polymer-319813_us-east1_cluster-2
    contexts:
    - context:
        cluster: gke_key-polymer-319813_us-east1_cluster-2
        user: gke_key-polymer-319813_us-east1_cluster-2
      name: gke_key-polymer-319813_us-east1_cluster-2
    current-context: gke_key-polymer-319813_us-east1_cluster-2
    kind: Config
    preferences: {}
    users:
    - name: gke_key-polymer-319813_us-east1_cluster-2
      user:
        auth-provider:
          config:
            access-token: ya29.a0ARrdaM9R4rQhgQTyeLLF7pFcBAMTdiPRRkKDoq9jDg-q9h9F6ENIdgoQu9kX_AD1t3kURnfOU1xDfoFJ5NYYV4Y3Rh3M-OdNJIRBwH6J-9su3CcBzpm7bnMEduc46qHLwVk98MjuaRK1qKOP6iVVeruWZxqJ4n25Wp6ZYA
            cmd-args: config config-helper --format=json
            cmd-path: /snap/google-cloud-sdk/190/bin/gcloud
            expiry: "2021-07-27T15:25:45Z"
            expiry-key: '{.credential.token_expiry}'
            token-key: '{.credential.access_token}'
          name: gcp
---
apiVersion: v1
kind: Pod
metadata:
  name: saps-arrebol
  labels:
    app: saps-arrebol
spec:
  containers:
  # Main container of Arrebol
  - name: arrebol
    image: thiagoyeds/arrebol:k8s.requirements
    volumeMounts:
    - name: arrebolconf-volume
      mountPath: /service/config/
    ports:
    - containerPort: 8080
  # Container for postgres DB
  - name: postgresql
    image: postgres
    envFrom:
    - configMapRef:
        name: postgres-config
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: postgres-volume
    ports:
    - containerPort: 5432
  # Container for pgadmin
  - name: pgadmin
    image: dpage/pgadmin4
    envFrom:
    - configMapRef:
        name: pgadmin-config
    ports:
    - containerPort: 15432
  - name: sidecar
    image: ufcgsaps/sidecar-proxy:v1.18.6
    volumeMounts:
    - name: kubeconfig
      mountPath: /root/.kube/
    ports:
    - containerPort: 8001
  volumes:
  - name: arrebolconf-volume
    configMap: 
      name: arrebol-config
  - name: postgres-volume
    emptyDir: {}
  - name: kubeconfig
    configMap:
      name: kubeconfig
---
apiVersion: v1
kind: Service
metadata:
  name: saps-arrebol
spec:
  selector:
    app: saps-arrebol
  ports:
  - name: arrebol
    protocol: TCP
    port: 8080
    targetPort: 8080
